steps:
  # Build Memory MCP Server
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/memory-mcp-server', '-f', 'Dockerfile.memory', '.']
  
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/memory-mcp-server']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'memory-mcp-server'
      - '--image=gcr.io/$PROJECT_ID/memory-mcp-server'
      - '--platform=managed'
      - '--region=europe-west1'
      - '--allow-unauthenticated'
      - '--port=8002'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--set-env-vars=REDIS_URL=redis://localhost:6379'

timeout: '1200s' 