# Cloud Build configuration for multiagent restaurant
steps:
  # Build and deploy MCP Server
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mcp-server', './mcp-server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mcp-server']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcp-server'
      - '--image=gcr.io/$PROJECT_ID/mcp-server'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8002'
      - '--memory=1Gi'
      - '--cpu=1'

  # Build and deploy Sumiller Bot
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sumiller-bot', './sumiller-bot']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sumiller-bot']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sumiller-bot'
      - '--image=gcr.io/$PROJECT_ID/sumiller-bot'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8001'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--set-env-vars=MCP_SERVER_URL=https://mcp-server-[HASH]-uc.a.run.app'

  # Build and deploy Maitre Bot
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/maitre-bot', './maitre-bot']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/maitre-bot']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'maitre-bot'
      - '--image=gcr.io/$PROJECT_ID/maitre-bot'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--port=8000'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--set-env-vars=SUMILLER_URL=https://sumiller-bot-[HASH]-uc.a.run.app'

timeout: '1600s' 