[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv", "curl"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
    "cd sumiller-bot && pip install -r requirements.txt"
]

[start]
cmd = "python main.py" 